//
//  CastListPageTests.swift
//  SwiftCompartidoTests
//
//  Copyright (c) 2025
//

import Foundation
import Testing
@testable import SwiftCompartido

@Suite("CastListPage Tests")
struct CastListPageTests {

    // MARK: - Initialization Tests

    @Test("Creates cast list with auto-generated ID")
    func testAutoGeneratedID() {
        let castList = CastListPage(
            title: "Main Cast",
            position: 0,
            printDots: true,
            items: []
        )

        #expect(!castList.id.isEmpty)
        #expect(castList.title == "Main Cast")
        #expect(castList.position == 0)
        #expect(castList.printDots == true)
    }

    @Test("Creates cast list with explicit ID")
    func testExplicitID() {
        let id = "my-custom-id"
        let castList = CastListPage(
            id: id,
            title: "Supporting Cast",
            position: 1,
            printDots: false,
            items: []
        )

        #expect(castList.id == id)
    }

    // MARK: - Cast Member Tests

    @Test("Creates cast member with auto-generated ID")
    func testCastMemberAutoID() {
        let member = CastListPage.CastMember(
            role: "HAMLET",
            name: "Benedict Cumberbatch",
            position: 0
        )

        #expect(!member.id.isEmpty)
        #expect(member.role == "HAMLET")
        #expect(member.name == "Benedict Cumberbatch")
    }

    @Test("Cast members are Hashable")
    func testCastMemberHashable() {
        let member1 = CastListPage.CastMember(
            id: "same-id",
            role: "HAMLET",
            name: "Actor 1",
            position: 0
        )
        let member2 = CastListPage.CastMember(
            id: "same-id",
            role: "OPHELIA",
            name: "Actor 2",
            position: 1
        )

        let set: Set = [member1, member2]
        // Same ID means they're equal, so set should have only 1 item
        #expect(set.count == 1)
    }

    // MARK: - CRUD Operations Tests

    @Test("Adds new cast member")
    func testAddMember() {
        var castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: []
        )

        castList.addMember(role: "BERNARD", name: "Jason Manino")

        #expect(castList.items.count == 1)
        #expect(castList.items[0].role == "BERNARD")
        #expect(castList.items[0].name == "Jason Manino")
        #expect(castList.items[0].position == 0)
    }

    @Test("Adds multiple members with incremental positions")
    func testAddMultipleMembers() {
        var castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: []
        )

        castList.addMember(role: "HAMLET", name: "Actor 1")
        castList.addMember(role: "OPHELIA", name: "Actor 2")
        castList.addMember(role: "CLAUDIUS", name: "Actor 3")

        #expect(castList.items.count == 3)
        #expect(castList.items[0].position == 0)
        #expect(castList.items[1].position == 1)
        #expect(castList.items[2].position == 2)
    }

    @Test("Removes cast member by ID")
    func testRemoveMember() {
        let member1 = CastListPage.CastMember(
            id: "keep-me",
            role: "HAMLET",
            name: "Actor 1",
            position: 0
        )
        let member2 = CastListPage.CastMember(
            id: "delete-me",
            role: "OPHELIA",
            name: "Actor 2",
            position: 1
        )

        var castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: [member1, member2]
        )

        castList.removeMember(id: "delete-me")

        #expect(castList.items.count == 1)
        #expect(castList.items[0].id == "keep-me")
    }

    @Test("Remove non-existent member does nothing")
    func testRemoveNonExistent() {
        let member = CastListPage.CastMember(
            role: "HAMLET",
            name: "Actor",
            position: 0
        )

        var castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: [member]
        )

        castList.removeMember(id: "non-existent-id")

        #expect(castList.items.count == 1)
    }

    @Test("Updates cast member role")
    func testUpdateMemberRole() {
        let member = CastListPage.CastMember(
            id: "member-id",
            role: "HAMLET",
            name: "Benedict Cumberbatch",
            position: 0
        )

        var castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: [member]
        )

        castList.updateMember(id: "member-id", role: "CLAUDIUS")

        #expect(castList.items[0].role == "CLAUDIUS")
        #expect(castList.items[0].name == "Benedict Cumberbatch")
    }

    @Test("Updates cast member name")
    func testUpdateMemberName() {
        let member = CastListPage.CastMember(
            id: "member-id",
            role: "HAMLET",
            name: "Old Actor",
            position: 0
        )

        var castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: [member]
        )

        castList.updateMember(id: "member-id", name: "New Actor")

        #expect(castList.items[0].role == "HAMLET")
        #expect(castList.items[0].name == "New Actor")
    }

    @Test("Updates both role and name")
    func testUpdateBothFields() {
        let member = CastListPage.CastMember(
            id: "member-id",
            role: "HAMLET",
            name: "Old Actor",
            position: 0
        )

        var castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: [member]
        )

        castList.updateMember(id: "member-id", role: "OPHELIA", name: "New Actor")

        #expect(castList.items[0].role == "OPHELIA")
        #expect(castList.items[0].name == "New Actor")
    }

    @Test("Update non-existent member does nothing")
    func testUpdateNonExistent() {
        let member = CastListPage.CastMember(
            id: "member-id",
            role: "HAMLET",
            name: "Actor",
            position: 0
        )

        var castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: [member]
        )

        castList.updateMember(id: "non-existent", role: "NEW ROLE")

        #expect(castList.items[0].role == "HAMLET")
    }

    // MARK: - Sorting Tests

    @Test("sortedItems returns members in position order")
    func testSortedItems() {
        let member1 = CastListPage.CastMember(
            role: "Third",
            name: "Actor 3",
            position: 2
        )
        let member2 = CastListPage.CastMember(
            role: "First",
            name: "Actor 1",
            position: 0
        )
        let member3 = CastListPage.CastMember(
            role: "Second",
            name: "Actor 2",
            position: 1
        )

        let castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: [member1, member2, member3]
        )

        let sorted = castList.sortedItems

        #expect(sorted[0].role == "First")
        #expect(sorted[1].role == "Second")
        #expect(sorted[2].role == "Third")
    }

    @Test("sortedItems handles gaps in positions")
    func testSortedItemsWithGaps() {
        let member1 = CastListPage.CastMember(
            role: "Position 5",
            name: "Actor",
            position: 5
        )
        let member2 = CastListPage.CastMember(
            role: "Position 1",
            name: "Actor",
            position: 1
        )
        let member3 = CastListPage.CastMember(
            role: "Position 10",
            name: "Actor",
            position: 10
        )

        let castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: [member1, member2, member3]
        )

        let sorted = castList.sortedItems

        #expect(sorted[0].position == 1)
        #expect(sorted[1].position == 5)
        #expect(sorted[2].position == 10)
    }

    // MARK: - Codable Tests

    @Test("Encodes and decodes correctly")
    func testCodable() throws {
        let original = CastListPage(
            id: "test-id",
            title: "Main Cast",
            position: 0,
            printDots: true,
            items: [
                CastListPage.CastMember(
                    id: "member-1",
                    role: "BERNARD",
                    name: "Jason Manino",
                    position: 0
                ),
                CastListPage.CastMember(
                    id: "member-2",
                    role: "SYLVIA",
                    name: "Lisa McMillan",
                    position: 1
                )
            ]
        )

        let encoded = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(CastListPage.self, from: encoded)

        #expect(decoded.id == original.id)
        #expect(decoded.title == original.title)
        #expect(decoded.position == original.position)
        #expect(decoded.printDots == original.printDots)
        #expect(decoded.items.count == 2)
        #expect(decoded.items[0].role == "BERNARD")
        #expect(decoded.items[1].role == "SYLVIA")
    }

    @Test("Encoded JSON includes type field")
    func testEncodedJSONHasType() throws {
        let castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: []
        )

        let encoded = try JSONEncoder().encode(castList)
        let json = try JSONSerialization.jsonObject(with: encoded) as? [String: Any]

        #expect(json?["type"] as? String == "castList")
    }

    // MARK: - Edge Cases

    @Test("Handles empty name")
    func testEmptyName() {
        var castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: []
        )

        castList.addMember(role: "BERNARD", name: "")

        #expect(castList.items[0].name.isEmpty)
    }

    @Test("Handles special characters in role and name")
    func testSpecialCharacters() {
        var castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: []
        )

        castList.addMember(role: "O'BRIEN", name: "Seán O'Casey")

        #expect(castList.items[0].role == "O'BRIEN")
        #expect(castList.items[0].name == "Seán O'Casey")
    }

    @Test("Handles very long strings")
    func testLongStrings() {
        let longRole = String(repeating: "A", count: 500)
        let longName = String(repeating: "B", count: 500)

        var castList = CastListPage(
            title: "Cast List",
            position: 0,
            items: []
        )

        castList.addMember(role: longRole, name: longName)

        #expect(castList.items[0].role.count == 500)
        #expect(castList.items[0].name.count == 500)
    }
}
